spring:
  datasource:
    url: jdbc:mysql://192.168.117.150:3306/quartz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true
    username: root
    password: root
    # 配置MySQL的驱动程序类，这里需要注意一下驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin #用户名
        login-password: admin #密码
        enabled: true
        allow:  # IP白名单 (没有配置或者为空，则允许所有访问)
        deny:   # IP黑名单 (存在共同时，deny优先于allow)
      web-stat-filter:  #配置druid过滤规则
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*" # 忽略资源
mybatis:
  config-location: classpath:mybatis.xml # 配置mybatis文件所在
  type-aliases-package: vip.xjdai.druid.model
  mapper-locations: classpath:mapper/*.xml # 配置mapper文件
server:
  port: 8099