
#spring boot从控制台打印出来的日志级别只有ERROR, WARN 还有INFO，如果你想要打印debug级别的日志：debug=true
#debug: trueg
#logging:
#  level:
#  # 配置文件名称
#  file:
#  #配置文件输出路径
#  path:

# logback配置文件路径；如果配置文件放在根目录，则无需配置
#logging:
#  config: classpath:logback.xml


spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.6.10/test?characterEncoding=UTF-8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
      username: root
      password: 12345678
      # 配置MySQL的驱动程序类，这里需要注意一下驱动
      driver-class-name: com.mysql.jdbc.Driver
      # 配置当前要使用的数据源的操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  output:
    ansi:
      enabled: detect
